{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: exception!", "trace": "def test_broken():\n>       raise Exception(\"exception!\")\nE       Exception: exception!\n\n02test_Allure2.py:22: Exception"}, "start": 1638075101607, "stop": 1638075101607, "uuid": "773c0fde-ff06-4f1e-897b-ca35f5083505", "historyId": "9917a7f28cd9aef890ca7cfd2cff6cc2", "testCaseId": "72fa12e73a8caa5f412d25ac85ff739a", "fullName": "02test_Allure2#test_broken", "labels": [{"name": "suite", "value": "02test_Allure2"}, {"name": "host", "value": "huixdeMacBook-Pro.local"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "02test_Allure2"}]}